### ISSUE TITLE
JDBC URL host is hardcoded - breaks in non-local Docker setups

### ISSUE THREAD

**Issue by rnorth** [revolut-engineering/jooq-plugin#3]
Hi,
Firstly, thanks for the nice plugin - this wraps up the tools so neatly!

I've encountered an issue which is unfortunately a blocker in our CI environment: the [JDBC URL host is hardcoded](https://github.com/revolut-engineering/jooq-plugin/blob/master/src/main/kotlin/com/revolut/jooq/JooqExtension.kt#L9) to `127.0.0.1`. Sadly our CI environment exposes the docker host at a different address - we have a slightly complicated DinD setup that makes this so, although the problem would also occur for users who run Docker on a different host to their CI workers.

I can think of a couple of possible ways around this:

1. allow `HOST` to be set via configuration or an environment variable (easiest, least preferable as a user)
2. derive `HOST` from `DOCKER_HOST` (if set, and of scheme tcp/http/https)
3. for full DinD-friendliness, derive `HOST` from both `DOCKER_HOST` and detected DinD state. The most comprehensive, battle-tested code I know of to do this is in [testcontainers-java's DockerClientConfigUtils](https://github.com/testcontainers/testcontainers-java/blob/master/core/src/main/java/org/testcontainers/dockerclient/DockerClientConfigUtils.java#L48) (full disclosure - I'm a maintainer!)

I suspect that the most pragmatic approach would be (2), but would be keen to get your thoughts on this and to hear whether you'd like a PR.

**Comment by adrianskrobaczrevolut** [comment]
Hello @rnorth 
I'm happy to hear you found the plugin usefull 👍

Thank you for the detailed explanation of the problem and indeed I didn't think about remote docker setup. You laid out our options nicely and since I like to keep things simple for the users(if something can be figured out lets figure it out for them 😄) I'd say let's go for the 2nd or 3rd option.

We can nicely incorporate this logic into the [Docker class](https://github.com/revolut-engineering/jooq-plugin/blob/master/src/main/kotlin/com/revolut/jooq/Docker.kt), get the url from the docker client, resolve the host based on it and pass it down to the task via [Docker#runInContainer action](https://github.com/revolut-engineering/jooq-plugin/blob/master/src/main/kotlin/com/revolut/jooq/Docker.kt#L27). I think we could start with the simplified version of the code you referenced without [defaultGateway path](https://github.com/testcontainers/testcontainers-java/blob/master/core/src/main/java/org/testcontainers/dockerclient/DockerClientConfigUtils.java#L25). I'm not sure how common is is though, if it is we can go with the full blown approach.

Regarding PR it's always welcome 😃, so if you feel like implementing it go ahead, if not let me know I'll try to implement it sometime next week 🙂

**Comment by encodeering** [comment]
Hey @adrianskrobaczrevolut, this plugin really fills the gap!

Would it be possible to make the host configurable for now and to initialize it with a proper default as suggested by @rnorth once his PR becomes ready?

Our CI server is also based on a docker:dind service with `DOCKER_HOST` set to a TCP address and therefore not reachable by `127.0.0.1`. 

A configurable host would further be an option to everyone with a not-yet known configuration.

**Comment by adrianskrobaczrevolut** [comment]
I've added the simplified resolution strategy for the database host and plugin configuration properties to override it in case the strategy is wrong. It's released in the [0.1.5](https://github.com/revolut-engineering/jooq-plugin/releases/tag/0.1.5) and [0.2.5](https://github.com/revolut-engineering/jooq-plugin/releases/tag/0.2.5) versions. Try it out and let me know if it helped 🙂

**Comment by rnorth** [comment]
Thanks @adrianskrobaczrevolut - I had just started work on a PR when I realized you'd already done it!

From my testing this works perfectly; I still need to land some tweaks to our DinD environment for CI, but I've been able to test this offline and it's great.

Thanks for resolving this!

**Comment by encodeering** [comment]
Yes, I can also confirm that your changes work as expected. Many thanks!

**Comment by adrianskrobaczrevolut** [comment]
I'm happy to jest that :) In case you have any more problems do not hesitate to open another issue :)
